name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Repo
                uses: actions/checkout@v4

            -   name: List and Read file
                run: |
                    echo "My first GitHub Actions Job"
                    ls -la
                    cat README.md
            # -   name: List file
            #     run: ls
            # -   name: Read file
            #     run: cat README.md            
            -   name: Generate ASCII artwork
                run: cowsy -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt
